;**********************************************************************
; Description:
;   Define global constants used with ADC_*.asm.
;   
;**********************************************************************
; Notes:
;
;
;**********************************************************************


; ADC state constants
adcDone         EQU 0x07    ; New ADC value is complete
adcReInit       EQU 0x06    ; Reinitialize ADC
